import { defineCompilationTemplate } from '@hotelcut/compiler';

export const hostBrollTemplate = defineCompilationTemplate({
  id: 'hotel.host-broll',
  version: '1.0.0',
  name: 'Host presentation with B-roll',
  minDurationSeconds: 30,
  maxDurationSeconds: 60,
  slots: [
    {
      id: 'host.intro',
      track: 'main',
      role: 'a-roll',
      startBasisPoints: 0,
      endBasisPoints: 3_000,
      acceptedKinds: ['video'],
      requiredTags: ['welcome'],
      preferredTags: ['host', 'presenter', 'speech'],
      required: true,
      allowAssetReuse: true,
      audioPolicy: 'keep',
      transition: 'dissolve',
    },
    {
      id: 'host.body',
      track: 'main',
      role: 'a-roll',
      startBasisPoints: 3_000,
      endBasisPoints: 7_000,
      acceptedKinds: ['video'],
      requiredTags: ['room'],
      preferredTags: ['host', 'presenter', 'speech'],
      required: true,
      allowAssetReuse: true,
      audioPolicy: 'keep',
      transition: 'dissolve',
    },
    {
      id: 'host.close',
      track: 'main',
      role: 'a-roll',
      startBasisPoints: 7_000,
      endBasisPoints: 10_000,
      acceptedKinds: ['video'],
      requiredTags: ['booking'],
      preferredTags: ['host', 'presenter', 'speech'],
      required: true,
      allowAssetReuse: true,
      audioPolicy: 'keep',
      transition: 'dissolve',
    },
    {
      id: 'broll.lobby',
      track: 'broll',
      role: 'b-roll',
      startBasisPoints: 1_500,
      endBasisPoints: 3_000,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['lobby'],
      preferredTags: ['bright', 'wide'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'fade',
    },
    {
      id: 'broll.room',
      track: 'broll',
      role: 'b-roll',
      startBasisPoints: 4_500,
      endBasisPoints: 6_200,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['room'],
      preferredTags: ['clean', 'window'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'fade',
    },
    {
      id: 'broll.service',
      track: 'broll',
      role: 'b-roll',
      startBasisPoints: 7_000,
      endBasisPoints: 8_300,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['service'],
      preferredTags: ['staff', 'detail'],
      required: false,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'fade',
    },
  ],
  captions: {
    safeAreaId: 'safe.caption',
    fontToken: 'brand.bodyFont',
    colorToken: 'brand.onPrimary',
    backgroundColorToken: 'brand.captionBackground',
    fontSize: 54,
    maxVisualWidth: 18,
    maxLines: 2,
  },
  title: {
    startBasisPoints: 0,
    endBasisPoints: 1_200,
    safeAreaId: 'safe.title',
    fontToken: 'brand.headingFont',
    colorToken: 'brand.onPrimary',
    backgroundColorToken: 'brand.captionBackground',
    fontSize: 68,
  },
  cta: {
    startBasisPoints: 8_200,
    endBasisPoints: 10_000,
  },
  music: {
    requiredTags: ['music'],
    preferredTags: ['warm', 'hotel'],
    volume: 0.18,
    fadeDurationFrames: 30,
  },
});
