import { defineCompilationTemplate } from '@hotelcut/compiler';

export const promotionTemplate = defineCompilationTemplate({
  id: 'hotel.promotion',
  version: '1.0.0',
  name: 'Hotel promotion video',
  minDurationSeconds: 15,
  maxDurationSeconds: 25,
  slots: [
    {
      id: 'promo.exterior',
      track: 'main',
      role: 'montage',
      startBasisPoints: 0,
      endBasisPoints: 2_200,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['exterior'],
      preferredTags: ['wide', 'day'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'promo.room',
      track: 'main',
      role: 'montage',
      startBasisPoints: 2_200,
      endBasisPoints: 5_200,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['room'],
      preferredTags: ['window', 'clean'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'promo.service',
      track: 'main',
      role: 'montage',
      startBasisPoints: 5_200,
      endBasisPoints: 7_600,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['service'],
      preferredTags: ['staff', 'welcome'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'promo.offer',
      track: 'main',
      role: 'montage',
      startBasisPoints: 7_600,
      endBasisPoints: 10_000,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['promotion'],
      preferredTags: ['food', 'weekend'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
  ],
  captions: null,
  title: {
    startBasisPoints: 0,
    endBasisPoints: 1_800,
    safeAreaId: 'safe.title',
    fontToken: 'brand.headingFont',
    colorToken: 'brand.onPrimary',
    backgroundColorToken: 'brand.captionBackground',
    fontSize: 74,
  },
  cta: {
    startBasisPoints: 8_200,
    endBasisPoints: 10_000,
  },
  music: {
    requiredTags: ['music'],
    preferredTags: ['energetic', 'weekend'],
    volume: 0.32,
    fadeDurationFrames: 24,
  },
});
