import { defineCompilationTemplate } from '@hotelcut/compiler';

export const roomMontageTemplate = defineCompilationTemplate({
  id: 'hotel.room-montage',
  version: '1.0.0',
  name: 'Room selling-point montage',
  minDurationSeconds: 15,
  maxDurationSeconds: 35,
  slots: [
    {
      id: 'room.exterior',
      track: 'main',
      role: 'montage',
      startBasisPoints: 0,
      endBasisPoints: 1_800,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['exterior'],
      preferredTags: ['day', 'wide'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'room.hero',
      track: 'main',
      role: 'montage',
      startBasisPoints: 1_800,
      endBasisPoints: 4_200,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['room'],
      preferredTags: ['window', 'bed'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'room.bathroom',
      track: 'main',
      role: 'montage',
      startBasisPoints: 4_200,
      endBasisPoints: 5_800,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['bathroom'],
      preferredTags: ['clean', 'detail'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'room.facility',
      track: 'main',
      role: 'montage',
      startBasisPoints: 5_800,
      endBasisPoints: 7_800,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['facility'],
      preferredTags: ['gym', 'pool'],
      required: false,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
    {
      id: 'room.detail',
      track: 'main',
      role: 'montage',
      startBasisPoints: 7_800,
      endBasisPoints: 10_000,
      acceptedKinds: ['video', 'image'],
      requiredTags: ['detail'],
      preferredTags: ['amenity', 'design'],
      required: true,
      allowAssetReuse: false,
      audioPolicy: 'mute',
      transition: 'dissolve',
    },
  ],
  captions: null,
  title: {
    startBasisPoints: 0,
    endBasisPoints: 1_500,
    safeAreaId: 'safe.title',
    fontToken: 'brand.headingFont',
    colorToken: 'brand.onPrimary',
    backgroundColorToken: 'brand.captionBackground',
    fontSize: 72,
  },
  cta: {
    startBasisPoints: 8_000,
    endBasisPoints: 10_000,
  },
  music: {
    requiredTags: ['music'],
    preferredTags: ['bright', 'travel'],
    volume: 0.35,
    fadeDurationFrames: 24,
  },
});
